
# Task 4:
# Develop a Jupyter Notebook (EDA.ipynb) that uses the cleaned data (cleaned_ebay_deals.csv) to perform the following analyses:
# 1.Time Series Analysis:
# convert timestamp col to datetime and sort data
# extract hour from each timestamp and group data by hr
# 2. price and discount analysis:
# plot histo and boxplot for product prices distribution
# create scatter plot comparing original_price and price
# plot distribution of discount_percentage to analyze how discount vary
# 3. Shipping Information Analysis:
# Count the frequency of different shipping options.
# Plot a bar chart showing the frequency of shipping options
# 4. Text Analysis on Product Titles:
# Define a set of keywords (e.g., "Apple", "Samsung", "Laptop", "iPhone", "Tablet", "Gimbal").
# Count how many times each keyword appears in the title column (case-insensitive).
# Visualize the keyword frequencies using a bar chart (ensuring the palette is set correctly).
# 5. Price Difference Analysis:
# Compute a new column for the absolute discount (i.e., original_price - price).
# Plot a histogram of the price differences.
# 6. Discount:
# Sort the dataset by discount_percentage in descending order and display the top 5 deals with the highest discounts.
# 
# Submission Requirements:
# Repository: Push your project to your GitHub repository. The repository should include:
# scraper.py
# clean_data.py
# The raw CSV file (ebay_tech_deals.csv) generated by the scraper.
# The cleaned CSV file (cleaned_ebay_deals.csv).
# EDA.ipynb (your Jupyter Notebook with EDA and visualizations).
# A GitHub Actions workflow file (with the cron expression 0 */3 * * * for scheduling).
# Documentation: Include a README or short report that summarizes your methodology, key findings from the EDA, challenges faced, and potential improvements.
# 

# Solution:

# task 1:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from datetime import datetime
import time
from fake_useragent import UserAgent
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

def scrape_ebay_data():
    """Scrape eBay tech deals and return as list of dicts."""
    # Set up Selenium options
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")

    # Rotate User-Agent
    ua = UserAgent()
    options.add_argument(f"user-agent={ua.random}")

    # ChromeDriver setup
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)

    driver.get("https://www.ebay.com/globaldeals/tech")

    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "div.dne-itemtile"))
    )

    # Scroll to load all items
    last_height = driver.execute_script("return document.body.scrollHeight")
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height

    # Extract product data
    products = driver.find_elements(By.CSS_SELECTOR, "div.dne-itemtile")
    data = []
    for product in products:
        try:
            title = product.find_element(By.XPATH, ".//span[@itemprop='name']").text
        except:
            title = "N/A"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        try:
            price = product.find_element(By.XPATH, ".//span[@itemprop='price']").text
        except:
            price = "N/A"
        try:
            original_price = product.find_element(By.CSS_SELECTOR, "span.itemtile-price-strikethrough").text
        except:
            original_price = "N/A"
        try:
            shipping = product.find_element(By.CSS_SELECTOR, "span.dne-itemtile-delivery").text
        except:
            shipping = "N/A"
        try:
            item_url = product.find_element(By.XPATH, ".//a[@itemprop='url']").get_attribute("href")
        except:
            item_url = "N/A"

        data.append({
            "title": title,
            "timestamp": timestamp,
            "price": price,
            "original_price": original_price,
            "shipping": shipping,
            "item_url": item_url
        })
        print(f"Extracted: {title}")

    driver.quit()
    return data

def save_to_csv(data):
    """Save scraped eBay data to CSV."""
    file_name = "ebay_tech_deals.csv"

    try:
        df = pd.read_csv(file_name)
    except FileNotFoundError:
        df = pd.DataFrame(columns=[
            "title", "timestamp", "price", "original_price", "shipping", "item_url"
        ])

    # Make a DataFrame for the new data rows
    new_rows = pd.DataFrame(data)

    # Append the new rows
    df = pd.concat([df, new_rows], ignore_index=True)

    # Save back to CSV
    df.to_csv(file_name, index=False)

if __name__ == "__main__":
    print("Scraping eBay tech deals...")
    scraped_data = scrape_ebay_data()  # now properly defined

    if scraped_data:
        save_to_csv(scraped_data)
        print("Data saved to ebay_tech_deals.csv")
    else:
        print("Failed to scrape data.")

# Task 3:
# Create a Python script (clean_data.py)
# load csv file "ebay_tech_deals.csv"
# all cols. as strings
# clean price and original_price cols to remove us $ and commas and trim extra white spaces
# if original_price is empty, replace with corresponding price
# Cleans the shipping column by replacing "N/A", empty strings, or strings containing only whitespace with the default message: "Shipping info unavailable".
# Converts the price and original_price columns to numeric (float) values.
# 
# Creates a new column discount_percentage computed as:
# discount_percentage = (1- ( price / original_price)) * 100
# (rounded to two decimal places, with missing values handled appropriately).
# 
# Saves the cleaned data as cleaned_ebay_deals.csv.
# 
