
# Task 4:
# Develop a Jupyter Notebook (EDA.ipynb) that uses the cleaned data (cleaned_ebay_deals.csv) to perform the following analyses:
# 1.Time Series Analysis:
# convert timestamp col to datetime and sort data
# extract hour from each timestamp and group data by hr
# 2. price and discount analysis:
# plot histo and boxplot for product prices distribution
# create scatter plot comparing original_price and price
# plot distribution of discount_percentage to analyze how discount vary
# 3. Shipping Information Analysis:
# Count the frequency of different shipping options.
# Plot a bar chart showing the frequency of shipping options
# 4. Text Analysis on Product Titles:
# Define a set of keywords (e.g., "Apple", "Samsung", "Laptop", "iPhone", "Tablet", "Gimbal").
# Count how many times each keyword appears in the title column (case-insensitive).
# Visualize the keyword frequencies using a bar chart (ensuring the palette is set correctly).
# 5. Price Difference Analysis:
# Compute a new column for the absolute discount (i.e., original_price - price).
# Plot a histogram of the price differences.
# 6. Discount:
# Sort the dataset by discount_percentage in descending order and display the top 5 deals with the highest discounts.
# 
# Submission Requirements:
# Repository: Push your project to your GitHub repository. The repository should include:
# scraper.py
# clean_data.py
# The raw CSV file (ebay_tech_deals.csv) generated by the scraper.
# The cleaned CSV file (cleaned_ebay_deals.csv).
# EDA.ipynb (your Jupyter Notebook with EDA and visualizations).
# A GitHub Actions workflow file (with the cron expression 0 */3 * * * for scheduling).
# Documentation: Include a README or short report that summarizes your methodology, key findings from the EDA, challenges faced, and potential improvements.
# 

# Solution:

# task 1:

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from datetime import datetime
import time
import csv
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

options = Options()
options.binary_location = "/usr/bin/chromium-browser"
options.add_argument("--headless=new")
options.add_argument("--window-size=1920,1080")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=options)

driver.get("https://www.ebay.com/globaldeals/tech")
# Task 1:
# scraping la ebay
# lazy loading of all products listing
# extract title timestamp price orgininal_price shipping item_url of products
# save to csv file the data "ebay_tech_deals.csv"
# don't impose limit on nb of products to extract

WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, "div.dne-itemtile"))
)

last_height = driver.execute_script("return document.body.scrollHeight")
while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

products = driver.find_elements(By.CSS_SELECTOR, "div.dne-itemtile")

data = []
for product in products:
    try:
        title = product.find_element(By.XPATH, ".//span[@itemprop = 'name']" ).text
    except:
        title = "N/A"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    try:
        # use itemprop = "price"
        price = product.find_element(By.XPATH, ".//span[@itemprop = 'price']" ).text
    except:
        price = "N/A"
    try:
        original_price = product.find_element(By.CSS_SELECTOR, "span.itemtile-price-strikethrough").text
    except:
        original_price = "N/A"
    try:
        shipping = product.find_element(By.CSS_SELECTOR, "span.dne-itemtile-delivery").text
    except:
        shipping = "N/A"
    try:
        item_url = product.find_element(By.XPATH, ".//a[@itemprop = 'url']" ).get_attribute("href")
    except:
        item_url = "N/A"

    data.append({
        "title": title,
        "timestamp": timestamp,
        "price": price,
        "original_price": original_price,
        "shipping": shipping,
        "item_url": item_url
    })
    print(f"Extracted: {title}")

import os

file_exists = os.path.isfile("ebay_tech_deals.csv")

with open("ebay_tech_deals.csv", "a", newline="", encoding="utf-8") as csvfile:
    fieldnames = ["title","timestamp","price","original_price","shipping","item_url"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    if not file_exists:
        writer.writeheader()

    writer.writerows(data)

driver.quit()


# Task 3:
# Create a Python script (clean_data.py)
# load csv file "ebay_tech_deals.csv"
# all cols. as strings
# clean price and original_price cols to remove us $ and commas and trim extra white spaces
# if original_price is empty, replace with corresponding price
# Cleans the shipping column by replacing "N/A", empty strings, or strings containing only whitespace with the default message: "Shipping info unavailable".
# Converts the price and original_price columns to numeric (float) values.
# 
# Creates a new column discount_percentage computed as:
# discount_percentage = (1- ( price / original_price)) * 100
# (rounded to two decimal places, with missing values handled appropriately).
# 
# Saves the cleaned data as cleaned_ebay_deals.csv.
# 
