name: Run eBay Scraper

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:   

permissions:
  contents: write

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install selenium pandas webdriver-manager fake-useragent matplotlib seaborn

      - name: Run scraping script
        run: python scraper.py

      - name: Run cleaning script
        run: python clean_data.py

      - name: Commit updated CSVs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull
          git add ebay_tech_deals.csv cleaned_ebay_deals.csv
          git commit -m "Update raw and cleaned data" || echo "No changes"
          git push